<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 /Users/auto/development/threlte_project/myblendermodel/static/models/human.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  ref = new Group()

  type ActionName = 'Armature|mixamo.com|Layer0'
  type GLTFResult = {
    nodes: {
      Fitness_Grandma_BodyGeo_1: THREE.SkinnedMesh
      Fitness_Grandma_BodyGeo_2: THREE.SkinnedMesh
      Fitness_Grandma_BrowsAnimGeo: THREE.SkinnedMesh
      Fitness_Grandma_EyesAnimGeo: THREE.SkinnedMesh
      Fitness_Grandma_MouthAnimGeo: THREE.SkinnedMesh
      mixamorigHips: THREE.Bone
    }
    materials: {
      Grandma_MAT: THREE.MeshStandardMaterial
      Lens_MAT: THREE.MeshStandardMaterial
      FitGrandma_Brows_MAT1: THREE.MeshStandardMaterial
      FitGrandma_Eyes_MAT1: THREE.MeshStandardMaterial
      FitGrandma_Mouth_MAT1: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/human.glb')

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Group
        name="Armature"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <T is={gltf.nodes.mixamorigHips} />
        <T.Group name="Fitness_Grandma_BodyGeo">
          <T.SkinnedMesh
            name="Fitness_Grandma_BodyGeo_1"
            geometry={gltf.nodes.Fitness_Grandma_BodyGeo_1.geometry}
            material={gltf.materials.Grandma_MAT}
            skeleton={gltf.nodes.Fitness_Grandma_BodyGeo_1.skeleton}
          />
          <T.SkinnedMesh
            name="Fitness_Grandma_BodyGeo_2"
            geometry={gltf.nodes.Fitness_Grandma_BodyGeo_2.geometry}
            material={gltf.materials.Lens_MAT}
            skeleton={gltf.nodes.Fitness_Grandma_BodyGeo_2.skeleton}
          />
        </T.Group>
        <T.SkinnedMesh
          name="Fitness_Grandma_BrowsAnimGeo"
          geometry={gltf.nodes.Fitness_Grandma_BrowsAnimGeo.geometry}
          material={gltf.materials.FitGrandma_Brows_MAT1}
          skeleton={gltf.nodes.Fitness_Grandma_BrowsAnimGeo.skeleton}
        />
        <T.SkinnedMesh
          name="Fitness_Grandma_EyesAnimGeo"
          geometry={gltf.nodes.Fitness_Grandma_EyesAnimGeo.geometry}
          material={gltf.materials.FitGrandma_Eyes_MAT1}
          skeleton={gltf.nodes.Fitness_Grandma_EyesAnimGeo.skeleton}
        />
        <T.SkinnedMesh
          name="Fitness_Grandma_MouthAnimGeo"
          geometry={gltf.nodes.Fitness_Grandma_MouthAnimGeo.geometry}
          material={gltf.materials.FitGrandma_Mouth_MAT1}
          skeleton={gltf.nodes.Fitness_Grandma_MouthAnimGeo.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
